---
- name: Quiz 2
  hosts: serverb.test.com
  tasks:
    - name: Install need pkg
      dnf:
        name: 
          - php
          - php-mysqlnd
          - httpd
          - vsftpd
          - mariadb-server
        state: present
    - name: Start Service and Enable for Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: Start Service and Enable for MariaDB
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: Start Service and Enable for vsftpd
      ansible.builtin.service:
        name: vsftpd
        state: started
        enabled: yes
    - name: permit traffic in default zone for service (http)
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: permit traffic in default zone for service (http)
      ansible.posix.firewalld:
        service: ftp
        permanent: true
        immediate: true
        state: enabled
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./1.php
        dest: /var/www/html/index.php
        mode: '0644'