---
- name: Quiz 2
  hosts: serverb.test.com
  vars_files: vars/quiz2_pkg.yaml
  tasks:
    - name: Install need pkg
      dnf:
        name:
          - "{{ web_pkg }}"
          - "{{ lang_pkg }}"
          - "{{ lang_db_pkg }}"
          - "{{ db_pkg }}"
          - "{{ ftp_pkg }}"
        state: present
    - name: Start Service and Enable for web
      ansible.builtin.service:
        name: "{{ web_pkg }}"
        state: started
        enabled: yes
    - name: Start Service and Enable for db
      ansible.builtin.service:
        name: "{{ db }}"
        state: started
        enabled: yes
    - name: Start Service and Enable for ftp
      ansible.builtin.service:
        name: "{{ ftp_pkg }}"
        state: started
        enabled: yes
    - name: permit traffic in default zone for service (http)
      ansible.posix.firewalld:
        service: "{{ web }}"
        permanent: true
        immediate: true
        state: enabled
    - name: permit traffic in default zone for service (ftp)
      ansible.posix.firewalld:
        service: "{{ ftp }}"
        permanent: true
        immediate: true
        state: enabled
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./1.php
        dest: /var/www/html/index.php
        mode: '0644'