---
- name: Install Server
  hosts: serverb.test.com
  tasks:
    - name: Install service PHP
      dnf:
        name: 'php'
        state: present
    - name: Install service PHP-mysqlnd
      dnf:
        name: 'php-mysqlnd'
        state: present

    - name: Install service Apache
      dnf:
        name: 'httpd'
        state: present
    - name: Start service Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: permit traffic in default zone for Apache service
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Install service MariaDB-Server
      dnf:
        name: 'mariadb-server'
        state: present
    - name: Start service MariaDB-Server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
    - name: permit traffic in default zone for DB service
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        immediate: true
        state: enabled

    - name: Install service vsftpd
      dnf:
        name: 'vsftpd'
        state: present
    - name: Start service vsftpd
      ansible.builtin.service:
        name: vsftpd
        state: started
        enabled: yes
    - name: permit traffic in default zone for ftp service
      ansible.posix.firewalld:
        service: ftp
        permanent: true
        immediate: true
        state: enabled
    
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./1.php
        dest: /var/www/html/index.php
        mode: '0644'