---
- name: ssh key login
  hosts: localhost
  tasks:
    - name: ssh key gen
      user:
        name: guru
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/guru/.ssh/id_rsa

- name: copy public key to server
  hosts: filesvr
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: guru
        state: present
        key: "{{ lookup('file', '/home/guru/.ssh/id_rsa.pub') }}"