---
- name: create group
  hosts: db
  tasks:
    - name: group add by group module
      ansible.builtin.group:
        name: docker
        state: present
        gid: 3220
    - name: add user
      ansible.builtin.user:
        name: hpe
        comment: docker
        uid: 2323
        group: docker