---
- name: ssh key login (Local)
  hosts: localhost
  tasks:
    - name: ssh keygen
      ansible.builtin.user:
        name: guru
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/guru/.ssh/id_rsa
        
- name: ssh key login (Remote)
  hosts: webdb
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: guru
        state: present
        key: "{{ lookup('file', '/home/guru/.ssh/id_rsa.pub') }}"

# SSH Key 오류 나오면 ansible-playbook -i hosts ssh.yml --ask-pass -vvvv 처음에 한 번 해볼 것